spring:
  mail:
    host: localhost
    port: 25
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          auth: false
          starttls:
            enable: false
          ssl:
            enable: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest